# Generated by Django 2.0.5 on 2018-06-08 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
